using System;
using System.IO;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Retro.Engine;

namespace Chapter10;

/// <summary>
/// Chapter 10 - Sourcing and Making Sound Effects.
///
/// A waveform viewer. It opens the WAV file itself, parses the RIFF header,
/// reads the samples and draws them. Everything in this book's audio was
/// generated by a fifty-line Python synthesiser, and this screen is how you look
/// at what came out.
///
/// Reading the header by hand is worth doing once. You will see for yourself
/// that a WAV is a trivial container - four-character chunk ids, a little-endian
/// length, and the samples - and stop treating audio files as magic.
/// </summary>
public sealed class Ch10Screen : IScreen
{
    private const int W = 224, H = 256;

    private static readonly string[] Bank =
    {
        "jump", "land", "step", "point", "hammer_get", "hammer_hit",
        "extra_life", "timer_warn", "death", "stage_clear", "blip", "select",
    };

    private readonly RetroGame _game;
    private int _index = -1;
    private int _pending;
    private float[] _peaks = Array.Empty<float>();
    private int _channels, _rate, _bits, _sampleCount;
    private string _error;

    public Ch10Screen(RetroGame game) => _game = game;

    public void Enter() => Load(0);
    public void Leave() { }

    public void Update(float dt)
    {
        if (_game.Input.Pressed(Btn.Down)) Load((_pending + 1) % Bank.Length);
        if (_game.Input.Pressed(Btn.Up)) Load((_pending + Bank.Length - 1) % Bank.Length);
        if (_game.Input.Pressed(Btn.Jump)) _game.Audio.Play(Bank[_pending], 0.9f, priority: 5);
    }

    /// <summary>Parse enough of a RIFF/WAVE file to draw it.</summary>
    private void Load(int index)
    {
        _pending = index;
        if (_index == index) return;
        _index = index;
        _error = null;
        try
        {
            using var stream = TitleContainer.OpenStream($"Content/{Bank[index]}.wav");
            using var ms = new MemoryStream();
            stream.CopyTo(ms);
            var data = ms.ToArray();

            if (data.Length < 12 || data[0] != 'R' || data[1] != 'I' || data[2] != 'F' || data[3] != 'F')
                throw new InvalidDataException("not RIFF");

            int pos = 12;
            int dataStart = -1, dataLength = 0;
            while (pos + 8 <= data.Length)
            {
                string id = System.Text.Encoding.ASCII.GetString(data, pos, 4);
                int len = BitConverter.ToInt32(data, pos + 4);
                int body = pos + 8;
                if (id == "fmt ")
                {
                    _channels = BitConverter.ToInt16(data, body + 2);
                    _rate = BitConverter.ToInt32(data, body + 4);
                    _bits = BitConverter.ToInt16(data, body + 14);
                }
                else if (id == "data")
                {
                    dataStart = body;
                    dataLength = Math.Min(len, data.Length - body);
                }
                pos = body + len + (len & 1);      // chunks are word aligned
            }
            if (dataStart < 0 || _bits != 16) throw new InvalidDataException("need 16-bit data");

            _sampleCount = dataLength / 2 / Math.Max(1, _channels);

            // Reduce to one peak per column - the only thing a 200px wide graph
            // can honestly show.
            const int Columns = 200;
            _peaks = new float[Columns];
            for (int c = 0; c < Columns; c++)
            {
                int from = (int)((long)c * _sampleCount / Columns);
                int to = (int)((long)(c + 1) * _sampleCount / Columns);
                float peak = 0f;
                for (int s = from; s < to; s++)
                {
                    int off = dataStart + s * 2 * _channels;
                    if (off + 1 >= data.Length) break;
                    float v = BitConverter.ToInt16(data, off) / 32768f;
                    peak = Math.Max(peak, Math.Abs(v));
                }
                _peaks[c] = peak;
            }
        }
        catch (Exception ex)
        {
            _error = ex.Message.ToUpperInvariant();
            _peaks = Array.Empty<float>();
        }
    }

    public void Draw(SpriteBatch batch)
    {
        var f = _game.Font;
        var px = _game.Assets.Pixel;

        f.DrawCentred(batch, "WAVEFORM", W / 2, 6, Theme.Accent);
        f.DrawCentred(batch, Bank[_index].Replace('_', ' ').ToUpperInvariant(), W / 2, 20, Theme.Ink);

        int gx = 12, gy = 40, gh = 80;
        batch.Draw(px, new Rectangle(gx, gy, 200, gh), Theme.Panel * Theme.PanelAlpha);
        batch.Draw(px, new Rectangle(gx, gy + gh / 2, 200, 1), Theme.InkFaint);

        for (int i = 0; i < _peaks.Length; i++)
        {
            int half = (int)(_peaks[i] * gh / 2);
            batch.Draw(px, new Rectangle(gx + i, gy + gh / 2 - half, 1, Math.Max(1, half * 2)),
                       Theme.Info);
        }

        int y = gy + gh + 14;
        if (_error != null)
        {
            f.Draw(batch, "ERROR " + _error, new Vector2(12, y), Theme.Warn);
        }
        else
        {
            float seconds = _rate > 0 ? _sampleCount / (float)_rate : 0f;
            f.Draw(batch, $"RATE     {_rate} HZ", new Vector2(12, y), Theme.Ink); y += 12;
            f.Draw(batch, $"BITS     {_bits}", new Vector2(12, y), Theme.Ink); y += 12;
            f.Draw(batch, $"CHANNELS {_channels}", new Vector2(12, y), Theme.Ink); y += 12;
            f.Draw(batch, $"SAMPLES  {_sampleCount}", new Vector2(12, y), Theme.Ink); y += 12;
            f.Draw(batch, $"LENGTH   {seconds:0.000} S", new Vector2(12, y), Theme.Ink); y += 12;
            f.Draw(batch, $"BYTES    {_sampleCount * 2 * Math.Max(1, _channels)}",
                   new Vector2(12, y), Theme.InkDim);
        }

        f.Draw(batch, "U D  PICK", new Vector2(12, H - 34), Theme.InkDim);
        f.Draw(batch, "FIRE PLAY", new Vector2(12, H - 22), Theme.InkDim);
    }
}
