// <auto-generated> Stage layouts. See tools/gen_climber_stages.py.
using Microsoft.Xna.Framework;

namespace Retro.Climber;

/// <summary>
/// The four stages, in the original's order: 25m barrels, 50m conveyors,
/// 75m elevators, 100m rivets. Girders are beams with sloping surfaces;
/// ladders are seated on the beams they join, which is computed rather than
/// typed so a ladder cannot stop short of a sloped girder.
/// </summary>
public static class ClimberStages
{
    public static int Count => 4;

    private static ClimberLevel Stage0()
    {
        return ClimberLevel.Create("25M BARRELS", 25, 5000)
            .Beam_(88f, 128f, 40f, 40f, 1)
            .Beam_(8f, 128f, 58f, 58f, 1)
            .Beam_(0f, 176f, 93.0f, 97.71428571428571f, 1)
            .Beam_(196f, 224f, 98.25f, 99.0f, 1)
            .Beam_(0f, 28f, 137.0f, 136.25f, 1)
            .Beam_(48f, 224f, 135.71428571428572f, 131.0f, 1)
            .Beam_(0f, 176f, 169.0f, 173.71428571428572f, 1)
            .Beam_(196f, 224f, 174.25f, 175.0f, 1)
            .Beam_(0f, 28f, 213.0f, 212.25f, 1)
            .Beam_(48f, 224f, 211.71428571428572f, 207.0f, 1)
            .Beam_(0f, 224f, 248f, 248f, 1)
            .Ladder_(14, 58f, 96f)
            .Ladder_(20, 97f, 133f)
            .Ladder_(8, 135f, 171f)
            .Ladder_(19, 173f, 209f)
            .Ladder_(11, 171f, 211f, broken: true)
            .Ladder_(9, 211f, 248f)
            .Ladder_(25, 208f, 248f, broken: true)
            .Gorilla(32f, 26f)
            .Girl(100f, 24f)
            .Barrels(76f, 54f)
            .Player(24f, 248f)
            .Oil(8f, 240f)
            .Fire(16f, 248f)
            .Hammer(72f, 211f)
            .Hammer(188f, 132f);
    }

    private static ClimberLevel Stage1()
    {
        return ClimberLevel.Create("50M CONVEYORS", 50, 6000)
            .Beam_(88f, 128f, 40f, 40f, 1)
            .Beam_(8f, 128f, 58f, 58f, 1)
            .Beam_(0f, 184f, 96.0f, 96.0f, 1, conveyor: true, beltDir: 1)
            .Beam_(204f, 224f, 96.0f, 96.0f, 1, conveyor: true, beltDir: 1)
            .Beam_(0f, 20f, 134.0f, 134.0f, -1, conveyor: true, beltDir: -1)
            .Beam_(40f, 224f, 134.0f, 134.0f, -1, conveyor: true, beltDir: -1)
            .Beam_(0f, 184f, 172.0f, 172.0f, 1, conveyor: true, beltDir: 1)
            .Beam_(204f, 224f, 172.0f, 172.0f, 1, conveyor: true, beltDir: 1)
            .Beam_(0f, 20f, 210.0f, 210.0f, -1, conveyor: true, beltDir: -1)
            .Beam_(40f, 224f, 210.0f, 210.0f, -1, conveyor: true, beltDir: -1)
            .Beam_(0f, 224f, 248f, 248f, 1)
            .Ladder_(14, 58f, 96f)
            .Ladder_(7, 96f, 134f)
            .Ladder_(20, 96f, 134f)
            .Ladder_(9, 134f, 172f)
            .Ladder_(19, 134f, 172f)
            .Ladder_(11, 172f, 210f)
            .Ladder_(18, 172f, 210f)
            .Ladder_(8, 210f, 248f)
            .Ladder_(21, 210f, 248f)
            .Gorilla(32f, 26f)
            .Girl(100f, 24f)
            .Player(16f, 248f)
            .Pies(4f, 96f)
            .Pies(220f, 134f)
            .Pies(4f, 172f)
            .Fire(200f, 248f)
            .Fire(60f, 210f)
            .Hammer(120f, 94f)
            .Hammer(64f, 170f);
    }

    private static ClimberLevel Stage2()
    {
        return ClimberLevel.Create("75M ELEVATORS", 75, 6000)
            .Beam_(88f, 128f, 2f, 2f, 1)
            .Beam_(56f, 152f, 58f, 58f, 1)
            .Beam_(48f, 168f, 96f, 96f, -1)
            .Beam_(0f, 60f, 134f, 134f, 1)
            .Beam_(0f, 60f, 172f, 172f, 1)
            .Beam_(0f, 60f, 210f, 210f, 1)
            .Beam_(148f, 224f, 134f, 134f, -1)
            .Beam_(148f, 224f, 172f, 172f, -1)
            .Beam_(148f, 224f, 210f, 210f, -1)
            .Beam_(0f, 224f, 248f, 248f, 1)
            .Ladder_(2, 134f, 172f)
            .Ladder_(2, 172f, 210f)
            .Ladder_(2, 210f, 248f)
            .Ladder_(26, 134f, 172f)
            .Ladder_(26, 172f, 210f)
            .Ladder_(26, 210f, 248f)
            .Ladder_(12, 58f, 96f)
            .Ladder_(8, 96f, 248f)
            .Gorilla(88f, 26f)
            .Girl(100f, 24f)
            .Player(16f, 248f)
            .Elevator(84f, 236f, 116f, 26f)
            .Elevator(124f, 236f, 116f, -26f)
            .Springs(162f, 96f)
            .Fire(30f, 172f)
            .Fire(196f, 172f)
            .Hammer(30f, 132f);
    }

    private static ClimberLevel Stage3()
    {
        return ClimberLevel.Create("100M RIVETS", 100, 6000)
            .Beam_(56f, 136f, 76f, 76f, 1)
            .Beam_(0f, 184f, 96.0f, 96.0f, 1)
            .Beam_(204f, 224f, 96.0f, 96.0f, 1)
            .Beam_(0f, 20f, 134.0f, 134.0f, 1)
            .Beam_(40f, 224f, 134.0f, 134.0f, 1)
            .Beam_(0f, 184f, 172.0f, 172.0f, 1)
            .Beam_(204f, 224f, 172.0f, 172.0f, 1)
            .Beam_(0f, 20f, 210.0f, 210.0f, 1)
            .Beam_(40f, 224f, 210.0f, 210.0f, 1)
            .Beam_(0f, 224f, 248f, 248f, 1)
            .Ladder_(12, 96f, 134f)
            .Ladder_(16, 96f, 134f)
            .Ladder_(9, 134f, 172f)
            .Ladder_(19, 134f, 172f)
            .Ladder_(12, 172f, 210f)
            .Ladder_(16, 172f, 210f)
            .Ladder_(8, 210f, 248f)
            .Ladder_(20, 210f, 248f)
            .Rivet(12f, 96f)
            .Rivet(204f, 96f)
            .Rivet(12f, 134f)
            .Rivet(204f, 134f)
            .Rivet(12f, 172f)
            .Rivet(204f, 172f)
            .Rivet(12f, 210f)
            .Rivet(204f, 210f)
            .Gorilla(60f, 44f)
            .Girl(116f, 60f)
            .Player(24f, 248f)
            .Fire(40f, 248f)
            .Fire(190f, 248f)
            .Fire(100f, 172f)
            .Hammer(112f, 132f);
    }

    public static ClimberLevel Load(int index) => (index % 4) switch
    {
        0 => Stage0(),
        1 => Stage1(),
        2 => Stage2(),
        3 => Stage3(),
        _ => Stage0(),
    };
}
