"""Writes Chapters.odt, the book's contents plan.

Generated from the chapter manifest rather than maintained by hand, for the same
reason the projects and the READMEs are: forty-six titles across four parts drift
the moment anything is renamed, and a contents document that disagrees with the
book is worse than none at all.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chapters
import gen_book
import odt

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "Chapters.odt")

TITLE = "Using MonoGame to Create Platform Games"
AUTHOR = "Paul F. Johnson"
REPO = "https://github.com/nodoid/monogame-platform-games"

WORD = {0: "Zero", 1: "One", 2: "Two", 3: "Three"}

BLURB = [
    "A single-screen climber in the classic arcade tradition and a flick-screen "
    "run-and-jump in the style of Ocean Software's *Hunchback*, both built in C# "
    "and MonoGame and both shipped to Android and iOS.",

    "Forty-six chapters, each nine to thirteen pages. Every chapter has its own "
    "runnable application for both platforms - ninety-two projects in all - and "
    "every graphic and sound is generated by a script included with the book.",

    "Each chapter opens with what it will teach, closes with a conclusion, and "
    "names the chapter that follows it.",
]

PART_BLURB = {
    0: "Material both games depend on: the loop and the fixed timestep, the "
       "virtual screen, sprites, input, animation, collision, screen flow, audio, "
       "and the high score table with its persistence.",
    1: "A portrait single-screen climber at 224x256, following four stages in "
       "order - 25m barrels, 50m conveyors, 75m elevators, 100m rivets - on "
       "sloping girders a stamping gorilla tilts into place during the opening. "
       "Barrels that take ladders, fireballs, cement pies, unkillable springs, a "
       "hammer, a bonus timer that doubles as the difficulty clock, three lives "
       "and arcade three-initial score entry.",
    2: "A landscape flick-screen run-and-jump at 256x192, turning back to "
       "portrait for its high score table. Sixteen hand-designed screens, ropes, "
       "arrows, patrolling knights, bouncing fireballs, fire pits, parallax "
       "backdrops, three lives and a clock that is the real antagonist.",
    3: "Performance and optimisation, settings and saves, packaging for both "
       "stores, and where to take the engine next.",
}


def body():
    out = [odt.para("h1", TITLE), odt.para("normal", AUTHOR)]
    for line in BLURB:
        out.append(odt.para("normal", line))
    out.append(odt.para("normal", f"Source: {REPO}"))

    for part, name, first, last in chapters.PARTS:
        out.append(odt.para("h1", f"Part {WORD[part]}: {name}"))
        out.append(odt.para("normal", PART_BLURB[part]))
        for ch in chapters.ALL:
            if first <= ch["num"] <= last:
                out.append(odt.para("h2", f"Chapter {ch['num']} - {ch['title']}"))
    return "".join(out)


def main():
    odt.write_odt(OUT, body(), gen_book.template_styles(), TITLE,
                  "A chapter plan")
    print(OUT)


if __name__ == "__main__":
    main()
